POST http://localhost:8080/events/1/register
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhaGFsQGdtYWlsLmNvbSIsImV4cCI6MTc3MDIzNDE1NiwidXNlcklkIjoyfQ.m5BF_R-f9pIBXEIaXKkixx8N2UrP0CZscUJVl8nYw0o